### ISSUE TITLE
Does it make sense to have a "Support not yet released" marker?

### ISSUE THREAD

**Issue by diamond-lizard** [schemedoc/srfi-metadata#16]
I'm kind of confused by why there's a "Support not yet released" marker in the SRFI Table.

The checkmark kind of makes it seem like the Scheme has support for that SRFI, but it actually doesn't.

Potentially, every Scheme's missing SRFI implementation could be marked as "Support not yet released".

It doesn't seem useful, and is confusing on top of that.

**Comment by jpellegrini** [comment]
It means there is support, but not in a stable released version (in a git checkout, for example).
It may be useful if I want to pick a Scheme implementation -- I may decide that it's ok for me to use an unreleased checkout from git, or I I may pick an implementation expecting to see the SRFI implemented in the near future.
I think it is useful, but perhaps the color used could be different?

**Comment by diamond-lizard** [comment]
Oh, ok.  I didn't understand that it meant that support was actually present, but only in an unstable release.  Knowing that is useful, I agree.

The color of this doesn't really matter to me.  As it is is fine, from where I sit.  As long as knowing that information is useful, it's fine.

**Comment by lassik** [comment]
Would "Supported in pre-release version" be clearer?

**Comment by jpellegrini** [comment]
> Would "Supported in pre-release version" be clearer?

I think it is!

**Comment by diamond-lizard** [comment]
> Would "Supported in pre-release version" be clearer?

I also think it's clearer.  Thank you.

**Comment by lassik** [comment]
Changed in commit 737255d. Accidentally committed it together with the bigger table update.
