### ISSUE TITLE
Where does the Ypsilon SRFI listing come from?

### ISSUE THREAD

**Issue by lassik** [schemedoc/srfi-metadata#2]
@erkin Do you remember where you got the Ypsilon listing? I can't find it anywhere.

**Comment by erkin** [comment]
I based it on contents of [`srfi`](https://github.com/imrehg/ypsilon/tree/master/sitelib/srfi) under the `sitelib` directory in the repo.

**Comment by lassik** [comment]
Great! Thanks.

SRFI 48 (Intermediate Format Strings) was included in the previous listing, but is not found by the scraper. It seems that it has been added after the release and is only available in the pre-release version.
