### ISSUE TITLE
Now live at doc.scheme.org

### ISSUE THREAD

**Issue by lassik** [schemedoc/srfi-metadata#21]
I uploaded the current table to https://doc.scheme.org/srfi/support/

@jpellegrini @diamond-lizard Let me know if you want access to upload files to the web server. @erkin is already on board.

**Comment by lassik** [comment]
(`docs.scheme.org` with a plural `s` is an alias for `doc`)

**Comment by jpellegrini** [comment]
Hi @lassik ! Is this to be announced already?

**Comment by lassik** [comment]
Not announced anywhere. The https://doc.scheme.org front page is just a placeholder page with a link to the table.

**Comment by lassik** [comment]
But feel free to pass the URL if you want to. To publish it in documentation, we should first decide on a stable URL. I improvised the current one without any thought.

**Comment by wasamasa** [comment]
This should be closed since it's live on docs.scheme.org now and doc.scheme.org shows a 404.

**Comment by lassik** [comment]
doc.scheme.org redirects to docs.scheme.org but relative URLs don't. Perhaps they should.
