### ISSUE TITLE
Chicken's support for many SRFIs not showing up on the SRFI Table 2020-11-21

### ISSUE THREAD

**Issue by diamond-lizard** [schemedoc/srfi-metadata#27]
Chicken 5 supports many SRFIs that for some reason are not showing up on the SRFI Table generated on 2020-11-21.

These SRFIs are:
* 27
* 47
* 51
* 67
* 74
* 78
* 95
* 137
* 141
* 143
* 178

All but three of these were both on the [Supported Standards](https://wiki.call-cc.org/supported-standards) and [Chicken SRFI Support](https://wiki.call-cc.org/srfi-support) wiki pages.  SRFIs 27, 95, and 178 were only on the latter.  I've just added them to the former myself.

All of these SRFIs also show up using the command Mario Domenech Goulart posted in the ["Re: Determining the correct, most up-to-date source/document for scraping CHICKEN SRFI metadata from"](https://lists.nongnu.org/archive/html/chicken-users/2020-11/msg00055.html) thread on the chicken-users mailing list:
```
wget --user=anonymous \
     --password="" \
     -qO - \
     http://code.call-cc.org/svn/chicken-eggs/release/5/egg-locations |\
     awk '/^\(srfi-/ {print substr($1, 2)}'
```

There is also the special case of SRFI-87, which is apparently supported, but not listed in any of these sources.  Please see [this thread](https://lists.nongnu.org/archive/html/chicken-users/2020-11/msg00115.html) for a discussion of this issue.

**Comment by lassik** [comment]
Thanks once again for reporting!

The code to scrape Chicken 5 built-in SRFIs is here: https://github.com/schemedoc/srfi-metadata/blob/85c6a7f226b8dc6a193eeadf3b5c48886e10415f/external.rkt#L86

It takes the "CHICKEN core -> CHICKEN 5" section of the "Supported standards" page. Some of the SRFIs you list are only mentioned in other parts of that page (in the C3 or C4 parts, or in the eggs part).

Here's the code to get SRFIs implemented as C5 eggs: https://github.com/schemedoc/srfi-metadata/blob/85c6a7f226b8dc6a193eeadf3b5c48886e10415f/external.rkt#L97

In fact, I just re-ran `./external.sh` and as it pulled the latest Chicken eggs data, it added the exact SRFI numbers you list. So apparently there was just a delay on their end in listing those eggs in the `egg-locations` file. Now it's fixed.
