### ISSUE TITLE
Legend for colors of SRFI status (withdrawn, superseded, draft, and final)

### ISSUE THREAD

**Issue by diamond-lizard** [schemedoc/srfi-metadata#28]
The colors corresponding to SRFI support status (Unsupported, Supported in latest version, etc) are shown in the Legend.

But the colors of the status of the SRFI itself (withdrawn, superseded, draft and final) are not.  The reader has to hover their mouse over the SRFI number to see the status described in words in the tooltip and make the inference themselves that that color corresponds to the SRFI status.

Should these colors be in the Legend too?

**Comment by lassik** [comment]
> Should these colors be in the Legend too?

Good idea.
