### ISSUE TITLE
Warn user if DOCKER_CONTENT_TRUST is set

### ISSUE THREAD

**Issue by jpellegrini** [schemedoc/srfi-metadata#29]
If it's set to 1, some containers will not run (at least STklos), but no error message will be issued.

**Comment by jpellegrini** [comment]
Wait, I'm not sure I'm using the right scripts or repository. Which repo shoulld be using for this?

**Comment by lassik** [comment]
I can't figure out right away what causes the problem. The bug report would probably belong in one of these repos:

* https://github.com/scheme-containers/stklos
* https://github.com/scheme-containers/project (if the same bug happens with more than one container)

**Comment by jpellegrini** [comment]
Oh, sorry! I think I was really confused when I opened this issue. I remembered something about srfi-metadata using containers to generate data, and when I ran some of the containers manually, it didn't work. Ok, will pay more attention next time

**Comment by lassik** [comment]
No problem at all :) srfi-metadata doesn't use containers; instead, it downloads bits of the source code of Scheme implementations via HTTP.
