### ISSUE TITLE
Unsyntax regexp is wrong

### ISSUE THREAD

**Issue by jpellegrini** [schemedoc/srfi-metadata#45]
I have fixed it, but didn't notice it's being auto-generated by the `listings.scm` script.
The patch was simple,

```
-       sed 's@%3a@@' |
+       sed 's/unsyntax-master.*src//' |
```

The new version would skip everything before `src/`, and henve not see all the numbers that are causing problems.
But it seems that the same Scheme script generates shell scripts for all implementations.

**Comment by lassik** [comment]
Ah, because that tar file from gitlab contains a commit hash like `unsyntax-master-144772eeef4a812dd79515b67010d33ad2e7e890` in all the filenames. And the commit hash contains numbers that randomly match SRFI numbers.

**Comment by jpellegrini** [comment]
> because that tar file from gitlab contains a commit hash

Yes! :)
