### ISSUE TITLE
Review what is being done to get info from Chicken

### ISSUE THREAD

**Issue by jpellegrini** [schemedoc/srfi-metadata#47]
Since some days ago, the `generate` script has been proposing to add SRFI 0 to Tinyscheme and to remove lots of SRFIs from Chicken.

```
$ diff --git a/data/chicken.scm b/data/chicken.scm
index 50f36f7..5448ec9 100644
--- a/data/chicken.scm
+++ b/data/chicken.scm
@@ -1,97 +1,25 @@
 0
-1
 2
 4
-5
 6
 8
 9
 10
 11
 12
-13
-14
 15
 16
 17
-18
-19
 23
-25
 26
-27
 28
-29
 30
 31
-34
... (lots of others here)
-197
-203
-207
-209
-216
-217
+98
```

Did the Chicken people change something that confused the script?
And does Tinyscheme really implement SRFI 0?

**Comment by lassik** [comment]
Yes, TinyScheme has SRFI 0 (`cond-expand`).

I don't know what causes the problems with Chicken.

**Comment by jpellegrini** [comment]
Ok, I commited a change for Tinyscheme; will check Chicken later

**Comment by jpellegrini** [comment]
Now that Tiny is OK, would this issue be a duplicate of #13 ?

**Comment by lassik** [comment]
Yes. Good call.
