### ISSUE TITLE
The server(https://docs.scheme.org/srfi/support/) is down 

### ISSUE THREAD

**Issue by APIPLM** [schemedoc/srfi-metadata#50]
[The server](https://docs.scheme.org/srfi/support/)  is down.

**Comment by APIPLM** [comment]
Now It is available.

**Comment by lassik** [comment]
There was a confusion between `doc.scheme.org` (singular) vs `docs.scheme.org` (plural). Plural seems to be more popular on other programming language sites, so I switched to it. `doc.scheme.org` is still an alias to `docs`, but relative URLs only work on `docs`.
