### ISSUE TITLE
Machine readable dataset

### ISSUE THREAD

**Issue by port19x** [schemedoc/srfi-metadata#56]
As an alternative/placeholder for #9, having a machine readable format be generated would help a lot.
JSON seems like a good idea, but I'm not opposed to sexps, edn, xml, or whatever.
This way I can write a layer 2 that uses the dataset directly, without resorting to error prone/brittle html parsing

**Comment by lassik** [comment]
IMHO the best default answer for `schemedoc` repos is to generate S-expressions, which are then turned into HTML and whatever else people need.

Currently the `listings/*.sh` shell scripts generate files into the `data` directory. The files contain lists of numbers.

**Comment by lassik** [comment]
A list of numbers parses as S-expressions, but is not very extensible.

I've been trying nudge most datasets I work on toward [POSE](https://github.com/s-expressions/pose), which is designed to be readable using the native `read` of most Lisp dialects.

**Comment by lassik** [comment]
A substantial example of POSE is [the file from which the scheme.org DNS zon and front page are generated](https://raw.githubusercontent.com/schemeorg/schemeorg/master/projects.pose).

**Comment by port19x** [comment]
I'm not sure I follow. 
Looking into the `data` directory of this repo, I only see a `.gitkeep` file.

You mean I can run the shell scripts to generate that data offline?
Is that what is happening on the server of docs.scheme.org?

If so, would you be open to either providing a raw endpoint, or generating the data via github actions, possibly onto a separate branch as to not pollute things?
That would be vaguely similar to github pages and could even be served through that

**Comment by lassik** [comment]
> You mean I can run the shell scripts to generate that data offline?

Yes.

> Is that what is happening on the server of docs.scheme.org?

No. Currently someone runs the scripts manually on his PC and then rsync's the result onto the server.

> If so, would you be open to either providing a raw endpoint, or generating the data via github actions, possibly onto a separate branch as to not pollute things?

It would probably be simplest to commit the data files into the repo. What do you think?

**Comment by port19x** [comment]
> It would probably be simplest to commit the data files into the repo

I agree, under the assumption that this data doesn't change more than once a week on average.
Anything beyond that calls for automation.

<details>
<summary>relevant xkcd</summary>
<img src="https://github.com/user-attachments/assets/22c2f31f-baae-48b3-9df8-4c17e114faa9">
</details>

**Comment by lassik** [comment]
@port19x Now the [data files has been committed](https://github.com/schemedoc/srfi-metadata/tree/master/data).
